[build]
  builder = "nixpacks"
  buildCommand = "./railway-build.sh"

[deploy]
  startCommand = "./railway-start.sh"
  healthcheckPath = "/"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10

[env]
  NODE_ENV = "production"
  PORT = "3000"